apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: a9w1ghs2u-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-1f2109c66f.wa9c.p3.openshiftapps.com/rhtap/rhtap-qe:6293ae4dd83515f5db754ca42ee4936741003523@sha256:aac418cf1e117a48181f6eca78374c90f27cfbf737fe54f282c9fa14839136da
          name: container-image
